//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relations
    {
        public short Id { get; set; }
        public short ParentId { get; set; }
    }
}
